services:
  armor:
    image: armor
    build: ./armor
    restart: always
    container_name: armor
    environment:
      - DUO_OAUTH2_CLIENT_SECRET=${DUO_OAUTH2_CLIENT_SECRET}
    ports:
      - 3000:3000
    command: ["armor"]
  reflector:
    image: reflector
    build: ./reflector
    restart: always
    container_name: reflector
    ports:
      - 8080:8080
    command: ["python3 /app/app.py"]
