# permissions for end users to edit armorproxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: armor-operator
    app.kubernetes.io/managed-by: kustomize
  name: armorproxy-editor-role
rules:
- apiGroups:
  - apps.armor.io
  resources:
  - armorproxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.armor.io
  resources:
  - armorproxies/status
  verbs:
  - get
