apiVersion: v1
kind: ConfigMap
metadata:
  name: armor-config-{{ .ServiceName }}
  namespace: armor
data:
  config.json: |
    {
      "server": {
        "host": "0.0.0.0",
        "port": 3000
      },
      "waf": {
        "enableCrs": {{ .Waf }},
        "customRulesPath": "",
        "crsRulesPath": "{{ .CrsRulesPath }}"
      },
      "proxy": {
        "targetHost": "{{ .TargetHost }}",
        "targetPort": {{ .TargetPort }}
      },
      "sam": {
        "database": "telegraf",
        "measurement": "armor"
      },
      "csp": {
        "policy": ""
      },
      "oidc": {
        "enable": {{ .Oidc }},
        "clientID": "{{ .OidcClientID }}",
        "providerUrl": "{{ .OidcProviderUrl }}",
        "redirectApplication": "{{ .OidcRedirectApplication }}"
      },
      "elasticsearch": {
        "enable": {{ .ElasticsearchEnable }},
        "url": [{{range $index, $url := .ElasticsearchURL}}{{if $index}}, {{end}}"{{$url}}"{{end}}]
      }
    }