apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: armor-{{ .ServiceName }}
  namespace: armor
spec:
  ingressClassName: {{ .IngressClassName }}
  rules:
  - host: {{ .IngressHost }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: armor-{{ .ServiceName }}
            port:
              number: 3000