apiVersion: v1
kind: Service
metadata:
  name: armor-{{ .ServiceName }}
  namespace: armor
spec:
  selector:
    app: armor-{{ .ServiceName }}
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP